name: Build Android App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Pembersihan & Persiapan Tempur
      run: |
        # Berikan izin eksekusi SEBELUM menjalankan apapun
        chmod +x ./gradlew
        # Hentikan gradle dengan paksa jika masih nyangkut
        ./gradlew --stop || true
        # Bersihkan cache dengan akses sudo agar tidak terkena permission denied
        sudo rm -rf /home/runner/.gradle/caches/
        sudo rm -rf app/build/

    - name: Build dengan Gradle
      run: ./gradlew assembleDebug

    - name: Upload hasil build
      uses: actions/upload-artifact@v4
      with:
        name: Youtube_Go_OSP
        path: app/build/outputs/apk/debug/app-debug.apk
        
